language: bash

env:
  - VERSION=0.0
services:
  - docker

before_install:
  - docker pull golang:1.12.0-stretch

script:
  - docker build . -t xthinker/go-builder:latest

after_success:
  - env
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build . -t xthinker/go-builder:latest
