language: bash

services:
  - docker

before_install:
  - docker pull golang:1.12.0-stretch

script:
  - docker build . -t xthinker/go-builder:$(cat VERSION)

after_success:
  - env
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push xthinker/go-builder:$(cat VERSION)
  - docker tag xthinker/go-builder:$(cat VERSION) xthinker/go-builder:latest
  - docker push xthinker/go-builder:latest
